services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "ollama serve & pid=$!; sleep 5; ollama pull llama3.2:1b; wait $pid"
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000" # Local development port
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CORS_ORIGINS=http://localhost,http://localhost:5173
      - ARTIFACT_DIR=/app/artifacts
      - OLLAMA_HOST=http://ollama:11434
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
      - ./backend/lakehouse.log:/app/lakehouse.log
      - ./backend/data:/app/data
      - ./backend/artifacts:/app/artifacts
    command: [ "uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    depends_on:
      - ollama
    restart: always
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8888:80"
  #   depends_on:
  #     - backend
  #   restart: always

volumes:
  ollama_data:
